### ISSUE TITLE
[BuildError] Solar2D Update Android Api to 32

### ISSUE THREAD

**Issue by stalker-66** [OneSignal/OneSignal-Solar2D-SDK#7]
Hello! Solar2D engine recently updated Android SDK API to 32. Now applications on Solar2D engine are not built with OneSignal plugin. Error in AndroidManifest.

17:34:23.914 > Task :App:processReleaseMainManifest FAILED
17:34:23.914 C:\Users\Narkoz\AppData\Local\Temp\Corona Labs\CLtmpa11620\template\app\src\main\AndroidManifest.xml Error:
17:34:23.914 Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

The reason is the OneSignal plugin for Android.

**Comment by jkasten2** [comment]
@stalker-66 Thanks for pointing this out, however this plugin is no longer under active development and this would be a larger change. If you would like to still use OneSignal with your Solar2D project you can use the [OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK) and [OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK) libraries in your project. However this requires native code and there currently isn't any official guides on doing this.

**Comment by stalker-66** [comment]
@jkasten2 😞

**Comment by stalker-66** [comment]
@jkasten2 😞
